#!/bin/bash

### install os package
function INSTALL_LINUX() {
  apt install pip python3 virtualenv
}

function INSTALL_MAC() {
  brew install pip3 python3 virtualenv
}

### create env
function CREATE_ENV() {
  virtualenv venv
}

### install requirements
function INSTALL_REQUIREMENT() {
  pip install -r requirements.txt
}

function INSTALL_REQUIREMENT_MAC() {
  pip3 install -r requirements.txt
}

if [[ ${1} = 'mac' ]]; then
  INSTALL_MAC
  CREATE_ENV
  INSTALL_REQUIREMENT_MAC
else
  INSTALL_LINUX
  CREATE_ENV
  INSTALL_REQUIREMENT
fi
